### ISSUE TITLE
Issue with Userscript

### ISSUE THREAD

**Issue by EuphoricPenguin** [Mathrandom7910/moomooapi#5]
Hello,
I don't know what the exact issue is, but I'm unable to use this as the example code suggests. I modified it a bit in the hopes that any health event would trigger my test alert, although I can't get this to behave no matter what I try. I've included my test code below in the hopes that it's something trivial that I may have missed.

```JS
// ==UserScript==
// @name         MooMoo Test
// @version      0.1
// @description  A quick test.
// @author       Mars&Bars
// @match        http://moomoo.io/*
// @require      https://raw.githubusercontent.com/Mathrandom7910/moomooapi/master/dist/MooMooAPI.umd.js
// ==/UserScript==
/*globals  MooMooAPI*/

const api = new MooMooAPI();

api.on("health", e => {
    if(e.health != 100) {
        alert("This is working.");
    }
});
```

**Comment by a-a-afk** [comment]
Does tampermonkey show the script being run on moomoo.io?
If not, try changing your match to this 
`// @match        *://*.moomoo.io/*`

**Comment by EuphoricPenguin** [comment]
> Does tampermonkey show the script being run on moomoo.io?
> If not, try changing your match to this 
> `// @match        *://*.moomoo.io/*`

Yes, it does. I'm thinking it's an issue with something else.

**Comment by a-a-afk** [comment]
After testing the userscript you provided, I noticed it was not importing or running the script. One fix I was able to find was explicitly declaring the grant as none with:
`// @grant        none`

**Comment by EuphoricPenguin** [comment]
This definitely worked, so thank you. It's been a while since I've done anything with user scripts, although I'm still confused as to what this metadata block is doing. Tampermonkey mentions that this is disabling a sandbox and running directly at the page context; GreaseSpot claims that not including the tag is equivalent to an implicit `@grant none`. I know that browsers sandbox each page for security reasons, but are user scripts in the extension themselves sandboxed in some fashion? If you know, I'm curious how this works.

**Comment by a-a-afk** [comment]
I'm not familiar with tampermonkey completely and I was unable to find why not putting the grant field vs grant none breaks the script. I assume it's because of tampermonkey's sandboxing to keep users more secure.
